Models/ErrorViewModel.cs
using System;

namespace FPSC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PizzaToOrder.cs
using FPSC.Data.DTO;
using FPSC.Data.Models;

namespace FPSC.Models
{
    public class PizzaToOrder
    {
        public PizzaMenuItemDTO  MenuItem { get; set; }
        public int Quantity { get; set; }
        public int NumberOfSlicesRequested { get; set; }
        public decimal TotalEstimatedPrice => MenuItem.Price * Quantity;
        public int NumberOfSlicesIncluded => MenuItem.PizzaSizeNumberOfSlices * Quantity;
    }
}

Models/SliceByPerson.cs
namespace FPSC.Models
{
    public class SliceByPerson
    {
        public string PizzaTypeName { get; set; }
        public int NumberOfSlicesRequested { get; set; }
        public string UserName { get; set; }
    }
}

Models/SummaryViewModel.cs
using FPSC.Data.DTO;
using System.Collections.Generic;
using System.Linq;

namespace FPSC.Models
{
    public class SummaryViewModel
    {
        public PizzaOrderDTO PizzaOrder { get; set; }
        public List<PizzaToOrder> PizzasToOrder { get; set; }
        public decimal GrandTotal => PizzasToOrder.Sum(p => p.TotalEstimatedPrice);
        public List<SliceByPerson> SliceByPeople { get; set; }
        public int TotalUsers => SliceByPeople.Select(s => s.UserName).Distinct().Count();
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace FPSC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/OrderController.cs
using FPSC.Data.DTO;
using FPSC.Models;
using FPSC.PizzaService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FPSC.Controllers
{
    public class OrderController : Controller
    {
        private IPizzaService _pizzaService;

        public OrderController(IPizzaService pizzaService)
        {
            _pizzaService = pizzaService;
        }

        public IActionResult Index()
        {
            //Readonly data
            ViewData["MenuItemsGrouped"] = _pizzaService.GetMenuGroupedByPizzaType();
            ViewData["PizzaTypes"] = _pizzaService.GetPizzaTypes(); //For partial view

            var order = new PizzaOrderDTO
            {
                Date = DateTime.Now,
                UserOrders = new List<PizzaUserOrderDTO>()
            };

            //order.UserOrders = new List<PizzaUserOrderDTO>
            //{
            //    new PizzaUserOrderDTO { UserName = "Bob", OrderItems = new List<PizzaUserOrderItemDTO>
            //    {
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 8 },
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 16 },
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 32 }
            //    } },
            //    new PizzaUserOrderDTO { UserName = "Catherine", OrderItems = new List<PizzaUserOrderItemDTO>
            //    {
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 4 },
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 8 },
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 2 }
            //    } },
            //    new PizzaUserOrderDTO { UserName = "Jaques", OrderItems = new List<PizzaUserOrderItemDTO>
            //    {
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 8 },
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 9 },
            //        new PizzaUserOrderItemDTO{ PizzaTypeId = 1, PizzaTypeName = "Meat lover", NumberOfSlices = 2 }
            //    } },
            //};

            return View(order);
        }

        [HttpPost]
        public IActionResult Summary(PizzaOrderDTO pizzaOrderDTO)
        {
            var summary = new SummaryViewModel();

            var menuItemsGrouped = _pizzaService.GetMenuGroupedByPizzaType();
            var pizzaTypes = _pizzaService.GetPizzaTypes();

            //Readonly data
            ViewData["MenuItemsGrouped"] = menuItemsGrouped;
            ViewData["PizzaTypes"] = pizzaTypes; //For partial view

            //Make order
            OrderPizza(pizzaOrderDTO);

            //Get best price value
            var nbSlicesByPizzaType = from order in pizzaOrderDTO.UserOrders
                                      from orderItem in order.OrderItems
                                      group orderItem by orderItem.PizzaTypeId into itemGroup
                                      select new
                                      {
                                          PizzaTypeName = pizzaTypes.FirstOrDefault(t=>t.PizzaTypeId == itemGroup.Key).Name,
                                          TotalSlices = itemGroup.Sum(i => i.NumberOfSlices)
                                      };

            var menu = _pizzaService.GetMenuGroupedByPizzaType();

            summary.PizzasToOrder = new List<PizzaToOrder>();
            foreach (var pizzaType in nbSlicesByPizzaType)
            {
                var priceBySize = from menuItem in menu.Where(m => m.Key == pizzaType.PizzaTypeName)
                                  from menuSize in menuItem
                                  select new PizzaToOrder
                                  {
                                      Quantity = (int)Math.Ceiling((decimal)pizzaType.TotalSlices / menuSize.PizzaSizeNumberOfSlices),
                                      MenuItem = menuSize,
                                      NumberOfSlicesRequested = pizzaType.TotalSlices
                                  };
                //Save best value
                var pizzaToOrder = priceBySize.OrderBy(p => p.TotalEstimatedPrice).FirstOrDefault();
                summary.PizzasToOrder.Add(pizzaToOrder);
            }

            //Users summary
            summary.SliceByPeople = pizzaOrderDTO.UserOrders.SelectMany(uo => uo.OrderItems.Select(i => new SliceByPerson
            {
                UserName = uo.UserName,
                PizzaTypeName = pizzaTypes.FirstOrDefault(t => t.PizzaTypeId == i.PizzaTypeId).Name,
                NumberOfSlicesRequested = i.NumberOfSlices
            })).ToList();

            return View(summary);
        }

        private void OrderPizza(PizzaOrderDTO pizzaOrderDTO)
        {
            var pizzaOrder = _pizzaService.CreatePizzaOrder();
            if (!pizzaOrder.Success)
                throw new NotImplementedException();

            foreach (var order in pizzaOrderDTO.UserOrders)
                _pizzaService.AddPizzaUserOrder(pizzaOrder.Data.PizzaOrderId, order);
        }
    }
}

Controllers/PizzaController.cs
using System.Collections.Generic;
using FPSC.Data.DTO;
using FPSC.Data.Models;
using FPSC.PizzaService;
using Microsoft.AspNetCore.Mvc;

namespace FPSC.Controllers
{
    [Route("api/[controller]")]
    public class PizzaController : Controller
    {
        private IPizzaService _pizzaService;

        public PizzaController(IPizzaService pizzaService)
        {
            _pizzaService = pizzaService;
        }

        [HttpGet("menu")]
        public List<PizzaMenuItemDTO> GetMenu() => _pizzaService.GetMenu();

        [HttpGet("order/{id:int}")]
        public ResultData<PizzaOrderDTO> GetPizzaOrder(int id) => _pizzaService.GetPizzaOrder(id);

        [HttpPost("order")]
        public ResultData<PizzaOrderDTO> CreatePizzaOrder() => _pizzaService.CreatePizzaOrder();

        [HttpPost("order/{id:int}/userOrder")]
        public Result AddPizzaOrderItem(int id, [FromBody] PizzaUserOrderDTO order) => _pizzaService.AddPizzaUserOrder(id, order);

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Familiprix challenge : Accepted</h1>

Views/Order/Index.cshtml
@model FPSC.Data.DTO.PizzaOrderDTO
@{
    ViewData["Title"] = "Index";
}

@section Init
{
    fpsc.order.init();
}

<h2>Nouvelle commande</h2>

<section>
    <h3>Menu</h3>
    <div class="row">
        @foreach (var pizzaType in ViewData["MenuItemsGrouped"] as List<IGrouping<string, PizzaMenuItemDTO>>)
        {
            <div class="col-sm-3">
                <b>@pizzaType.Key</b>
                <ul>
                    @foreach (var pizzaSize in pizzaType)
                    {
                        <li>@pizzaSize.PizzaSizeName = @pizzaSize.PizzaSizeNumberOfSlices slices, @pizzaSize.Price$</li>
                    }
                </ul>
            </div>
        }
    </div>
</section>
<section id="participants">
    <form asp-controller="Order" asp-action="Summary" method="post">
        <h3>Participants</h3>
        <div class="row">
            <div id="participantsList" class="col-md-12">
                @for (var i = 0; i < Model.UserOrders.Count; i++)
                {
                    var user = Model.UserOrders[i];

                    ViewData["UserOrderPrefix"] = "PizzaOrderDTO.UserOrders[" + i + "]";
                    @Html.Partial("_userOrderPartialView", user);
                }
            </div>
        </div>
        <div class="btn btn-success" data-action='addParticipant'>Add participant</div>
        <button class="btn btn-default" type="submit">Order</button>
    </form>
</section>

@section Scripts
    {
    <script id="template-UserOrder" type="text/template">
        @{ViewData["UserOrderPrefix"] = "PizzaOrderDTO.UserOrders[_idxI_]";}
        @Html.Partial("_userOrderPartialView", new PizzaUserOrderDTO() { OrderItems = new List<PizzaUserOrderItemDTO>() });
    </script>
    <script id="template-UserOrderItem" type="text/template">
        @{ViewData["UserOrderItemPrefix"] = ViewData["UserOrderPrefix"] + ".OrderItems[_idxJ_]";}
        @Html.Partial("_userOrderItemPartialView", new PizzaUserOrderItemDTO());
    </script>
}

Views/Order/Summary.cshtml
@model SummaryViewModel
@{
    ViewData["Title"] = "Index";
}

@section Init
    {
    $("#GrandTotal").change(function()
    {
    $("#TotalPerUser").val(parseFloat($("#GrandTotal").val())/@Model.TotalUsers);
    })
    $("#TotalPerUser").val(parseFloat($("#GrandTotal").val())/@Model.TotalUsers);
}

<h2>Order summary</h2>

<section>
    <h3>Menu</h3>
    <div class="row">
        @foreach (var pizzaType in ViewData["MenuItemsGrouped"] as List<IGrouping<string, PizzaMenuItemDTO>>)
        {
            <div class="col-sm-3">
                <b>@pizzaType.Key</b>
                <ul>
                    @foreach (var pizzaSize in pizzaType)
                    {
                        <li>@pizzaSize.PizzaSizeName = @pizzaSize.PizzaSizeNumberOfSlices slices, @pizzaSize.Price$</li>
                    }
                </ul>
            </div>
        }
    </div>
</section>
<section>
    <h3>Slices by person</h3>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Pizza</th>
                        <th>Username</th>
                        <th>Number of slices requested</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var sliceByPerson in Model.SliceByPeople)
                    {
                        <tr>
                            <td>@sliceByPerson.UserName</td>
                            <td>@sliceByPerson.PizzaTypeName</td>
                            <td>@sliceByPerson.NumberOfSlicesRequested</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>
<section>
    <h3>Pizzas to order</h3>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Quantity</th>
                        <th>Pizza</th>
                        <th>Number of slices requested</th>
                        <th>Number of slices included</th>
                        <th>Total estimated price</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var pizzaToOrder in Model.PizzasToOrder)
                    {
                        <tr>
                            <td>@pizzaToOrder.MenuItem.PizzaTypeName</td>
                            <td>@pizzaToOrder.Quantity</td>
                            <td>@pizzaToOrder.NumberOfSlicesRequested</td>
                            <td>@pizzaToOrder.NumberOfSlicesIncluded</td>
                            <td>@pizzaToOrder.TotalEstimatedPrice</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <label asp-for="@Model.GrandTotal"></label>
            <input class="form-control" asp-for="@Model.GrandTotal" />
        </div>
        <div class="col-sm-2">
            <label for="TotalPerUser">Total per user</label>
            <input class="form-control" id="TotalPerUser" name="TotalPerUser" />
        </div>
    </div>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Familiprix F-PSC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.bundle.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.bundle.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Familiprix F-PSC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Menu</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">Commander</a></li>
                    <li><a asp-area="" asp-controller="OrderHistory" asp-action="Index">Historique des commandes</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/fpsc.bundle.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/fpsc.bundle.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    @if (IsSectionDefined("Init"))
    {
        <script type="text/javascript">
            $(document).ready(function() {
              @RenderSection("Init", required: false)
            });
        </script>
    }
</body>
</html>

Views/Shared/_userOrderItemPartialView.cshtml
@model PizzaUserOrderItemDTO
@{
}

<tr>
    <td>
        <div class="form-group">
            <select class="form-control"
                    name="@(ViewData["UserOrderItemPrefix"].ToString() + ".PizzaTypeId")"
                    asp-for="@Model.PizzaTypeId"
                    asp-items="@(new SelectList((IEnumerable<PizzaTypeDTO>)ViewData["PizzaTypes"], "PizzaTypeId", "Name"))">
                <option>Select a pizza</option>
            </select>
        </div>
    </td>
    <td>
        <input name="@(ViewData["UserOrderItemPrefix"].ToString() + ".NumberOfSlices")" class="form-control" asp-for="@Model.NumberOfSlices" />
    </td>
    <td>
        <div class="btn btn-danger" data-action='deleteUserOrderItem'>X</div>
    </td>
</tr>

Views/Shared/_userOrderPartialView.cshtml
@model PizzaUserOrderDTO
@{
}

<div class="participantOrder">
    <div class="form-group">
        <label asp-for="@Model.UserName"></label>
        <div class="row">
            <div class="col-sm-3 col-xs-10">
                <input name="@(ViewData["UserOrderPrefix"].ToString() + ".UserName")" class="form-control" asp-for="@Model.UserName" />
            </div>
            <div class="col-sm-1 col-xs-2">
                <div class="btn btn-danger" data-action="deleteParticipant">X</div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Pizza</th>
                <th>Number of slices</th>
            </tr>
        </thead>
        <tbody>
            @for (var j = 0; j < Model.OrderItems.Count; j++)
            {
                var orderItem = Model.OrderItems[j];

                ViewData["UserOrderItemPrefix"] = ViewData["UserOrderPrefix"].ToString() + ".OrderItems[" + j + "]";
                @Html.Partial("_userOrderItemPartialView", orderItem);
            }
        </tbody>
    </table>
    <div class="btn btn-success" data-action="addUserOrderItem">Add pizza type</div>
</div>